### ISSUE TITLE
Check dependences on install

### ISSUE THREAD

**Issue by scith** [scith/rainloop_ynh#15]
$aRequirements = array(
'cURL' => function_exists('curl_init'),
'iconv' => function_exists('iconv'),
'json' => function_exists('json_decode'),
'DateTime' => class_exists('DateTime') && class_exists('DateTimeZone'),
'libxml' => function_exists('libxml_use_internal_errors'),
'dom' => class_exists('DOMDocument'),
'Zlib' => function_exists('gzopen') || function_exists('gzopen64'),
'PCRE' => function_exists('preg_replace'),
'SPL' => function_exists('spl_autoload_register')
);

See https://github.com/scith/rainloop_ynh/pull/14#issuecomment-157689030

**Comment by Djip007** [comment]
la page officiel: http://www.rainloop.net/docs/system-requirements/

**Comment by n00dl3** [comment]
Selon [Debian](https://packages.debian.org/jessie/php5-fpm) (j'ai vérifé c'est pareil pour wheezy):
 >The following extensions are built in: (...) dom (...) iconv libxml (...) pcre (...) SPL (...) zlib.

et php dit [à propos de DateTime](http://php.net/manual/en/datetime.installation.php):
>There is no installation needed to use these functions; they are part of the PHP core.

 ce qui nous donne:
 
* :x:  cURL 
* :white_check_mark: iconv 
* :x: json 
* :white_check_mark: DateTime 
* :white_check_mark: libxml 
* :white_check_mark: dom 
* :white_check_mark: Zlib 
* :white_check_mark: PCRE 
* :white_check_mark: SPL

Il faut donc juste rajouter un sudo `apt-get install -y php5-json php5-curl` dans le script d'installation
 (je m'en occupe).

**Comment by scith** [comment]
Merci :)

**Comment by Djip007** [comment]
sauf si c'est installé par yunohost par defaut...
la liste de base: https://github.com/YunoHost/yunohost-config/blob/unstable/debian/control
htop, vim, console-setup, acpi-support-base, gzip, bzip2, unzip, unrar|unrar-free, zoo, arj, libiconv-hook1, fail2ban, rsync, git-core, gettext, curl, dnsmasq | bind9, yunohost-config-postfix, yunohost-config-dovecot, yunohost-config-metronome, yunohost-config-others, yunohost-config-mysql, yunohost-config-slapd, ssowat, yunohost-admin, moulinette, moulinette-yunohost, yunohost-config-amavis, ntp, bash-completion

OK pour curl je dirais apres faut suivre les autres...

**Comment by Djip007** [comment]
pour yunohost-config-ngenx 
php5-fpm, php5-ldap, php5-mysql | php5-mysqlnd, php5-gd, php5-curl, php5-mcrypt, php5-intl, php-gettext, yunohost-config-others, nginx-extras (>=1.6.2)

**Comment by Djip007** [comment]
bizard pour json: http://php.net/manual/fr/json.installation.php
Je ne sais pas si il faut ou pas...

**Comment by n00dl3** [comment]
php5-cli est aussi une dépendance, et pourtant...

**Comment by Djip007** [comment]
en effet... pour debian/jessie 
les element installé pour Docker sont la je pense... https://github.com/YunoHost/Dockerfile/blob/master/Dockerfile

Je me demande si il manque pas une dependence sur  yunohost-config-ngenx ....
