### ISSUE TITLE
Domain loop

### ISSUE THREAD

**Issue by scith** [scith/rainloop_ynh#19]
See https://github.com/YunoHostPlugins-Testing/rainloop_ynh/issues/3

https://github.com/YunoHostPlugins-Testing/rainloop_ynh/blob/master/scripts/install#L88-L89
Suggest changing the "domain" variable in the loop into "domainadd"

**Comment by Djip007** [comment]
Pour ce cas (si tu as le temps...) tu peux peut-etre faire la modification en directe...
En tout cas si tu repart de la version dans t'on repos, que tu l'y corrige... tu peu faire le pull apres.
(Attention: je crois que je n'ai pas tout remis dans le repos Testing ou pas forcement sous cette forme...) Donc si tu fait pas la modif direct dans Testing, pense à mettre ta master au bon endroit)
