### ISSUE TITLE
Shared LDAP address book

### ISSUE THREAD

**Issue by scith** [scith/rainloop_ynh#2]
Setup the shared LDAP address book to autocomplete YunoHost users emails

See: https://github.com/polytan02/rainloop_ynh/issues/12

**Comment by scith** [comment]
@maniackcrudelis @polytan02 @Djip007 : avez-vous déjà réussi à paramétrer le carnet d'adresse LDAP ? J'ai tenté plusieurs paramétrages sans succès
Merci

**Comment by polytan02** [comment]
Le carnet d'adresses n'est pas géré par ldap mai par baikal.

Pour se connecter, en admettant que le domaine est domain.tld, que baikal à été installé dans le sous dossier /baikal et que l'utilisateur est bob, pour s'y connecté l'adresse est :  
https://domain.tld/baikal/card.php/addressbooks/bob/default

Ensuite il faut fournir à rainloop les détails de la bdd mysql dédiée à rainloop car les contacts sont synchronisés dedans.

Il faut également indiquer, par utilisateur, nom de login et mot de passe pour accéder via carddav aux contacts de l'utilisateur.

**Comment by maniackcrudelis** [comment]
Je ne suis pas sûr de bien comprendre ce que tu veux dire par "Carnet d'adresse LDAP".
Ce qui est sûr, du moins, c'est que je n'ai aucune intégration ldap configurée dans Rainloop.

En revanche, il doit bien y avoir une connexion ldap quelque part puisque rainloop créé lors de la connexion d'un nouvel user un espace qui lui est dédié avec son adresse mail dans sa configuration. Et se contente du mot de passe ldap de l'user pour s'authentifier sur rainloop.

**Comment by scith** [comment]
En fait je parlais d'avoir les autres utilisateurs YunoHost dans le carnet d'adresse (via le plugin "ldap-contacts-suggestions"). Il se base sur les emails des utilisateurs dans LDAP.

@polytan02 concernant Baïkal je vais essayer de préconfigurer ça via un Hook: https://github.com/scith/rainloop_ynh/issues/3

Merci

**Comment by maniackcrudelis** [comment]
C'est ce qui me semblait. J'ai pas essayé ce plugin. Et pour cause, je ne suis pas à jour...
Je jetterais un coup d'oeil après avoir fait la maj, je commence à prendre l'habitude de me battre avec ldap, je trouverais peut-être ;)

**Comment by Djip007** [comment]
Pas encore essayé... juste vu le plugins... mais c'est à ca que je pensais scith: sugéré les mail des autres utilisateurs...

Pour maniackcrudelis: si j'ai bien compris la filo de rainloop il ne se sert que de imap. il c'éé un compte pour chaque utilisateur si le domaine est autorisé et si il arrive a se connecté au ldap. 
Pour faire fonctionner rainloop il suffit d'un imap.

**Comment by polytan02** [comment]
Oui, le ldap est utilisé par yunohost et rainloop utilise imap. Le sso fait le lien entre tout ça. 

Après, je ne suis pas dev et tout cela me dépasse beaucoup :(

**Comment by maniackcrudelis** [comment]
Essai infructueux sur le plugin ldap-contacts-suggestions. Du moins, après configuration je n'en retrouve aucune mention et je ne trouve aucun contact de l'annuaire ldap.

Config suivante:
LDAP hostname: localhost
LDAP port: 389
Users DN format: ou=users,dc=yunohost,dc=org
objectClass value: uid
Name field: givenName
Mail field: mail
Allowed emails: *

Et le plugin n'est guère loquace, pas un log ni un message d'erreur à se mettre sous la dent...

**Comment by Djip007** [comment]
tu as trouver comment mettre les log?

les sources du plugins sont la: https://github.com/RainLoop/rainloop-webmail/blob/master/plugins/ldap-contacts-suggestions/LdapContactsSuggestions.php (ou sous data/..../plugins dans ton install)
normalement il y a des trace lor des connect/bind... etc surtout en cas d'erreur.

si je me rappel bien pour activé les log j'ai modifié le data/_data_/_default_/configs/application.ini
section:
[logs]
; Enable logging
enable = Off  => On

apres les logs sont dans  data/_data_/_default_/logs

**Comment by maniackcrudelis** [comment]
Je cherchais les logs dans /var/log...

Bon, ça sent le log de 50Go dans 3 jours, mais aucune info sur un quelconque échec de la connexion ldap.

```
[20:44:34.305][a4eed31f] AJAX[DATA]: {"Action":"AdminPluginList","Result":[{"Name":"ldap-contacts-suggestions","Enabled":true,"Configured":false}],"Time":11}
[20:44:35.329][de0e043b] POST[DATA]: {"Name":"ldap-contacts-suggestions","Action":"AdminPluginLoad","XToken":"219fad73c77e4147c187379581808006"}
[20:44:35.333][de0e043b] AJAX[DATA]: {"Action":"AdminPluginLoad","Result":{"Name":"ldap-contacts-suggestions","Readme":"","Config":[["localhost","hostname",0,"LDAP hostname","127.0.0.1","",""],[389,"port",1,"LDAP port",389,"",""],["","access_dn",0,"Access dn (login)","","",""],["********","access_password",3,"Access password","","",""]...
[20:44:39.899][da7862f2] POST[DATA]: {"Name":"ldap-contacts-suggestions","_hostname":"localhost","_port":"389","_access_dn":"","_access_password":"","_users_dn_format":"ou=users,dc=yunohost,dc=org","_object_class":"uid","_name_field":"givenName","_mail_field":"mail","_allowed_emails":"*","Action":"AdminPluginSettingsUpdate","XToken":"219fad73c77e4147c187379581808006"}
```

**Comment by polytan02** [comment]
Je ne sais pas si cela aide mais il y a une config de ldap yunohost là :
 https://github.com/abeudin/z-push_ynh/blob/master/conf/backend/config-imap.php#L179

**Comment by Djip007** [comment]
le plugins ldapadmin integré utilise:
cn=admin,dc=yunohost,dc=org

**Comment by scith** [comment]
ben la conf de ManiackCrudelis semble bonne ... J'avais tenté la même sans succès. Mais chez moi il s'obstine à vouloir entrer un mot de passe (mais c'est peut etre du à mon navigateur qui croit reconnaitre un champs)

Je vois rien dans les sources qui pourrait créer un soucis ...

**Comment by maniackcrudelis** [comment]
Pareil, le navigateur me rempli toujours le champs password. Mais le log indique bien une connexion sans mot de passe.

**Comment by Djip007** [comment]
Pas de succes non plus mais moi il me demande pas de mdp... mais surtout il essai jamais d'appeler le plugins... pas de connection dans le log... donc je doit avoir d'autre probleme ;)

**Comment by Djip007** [comment]
J'ai trouver un bug dans la connection mysql.... peut'etre que ca marchera mieux maintenant.. pas testé encore

**Comment by scith** [comment]
Je vais tester ça asap

**Comment by Djip007** [comment]
Ce qui est chiant c'est que l'on ne peu pas tester des branches... 
Je vais remettre en place ta solution pour le sso ... il faut que je le fasse avant de faure un pull request.

**Comment by Djip007** [comment]
Bon ca semble marché...
je met un pull request?

**Comment by Djip007** [comment]
Bon ca marche toujous pas... mais je sais pourquoi.
En fait ca vient d'un bug dans php... la fonction ldap_bind() renvoie toujours false... et donc la recherche s'arrete...  j'ai eu le meme probleme en codant mon plugins et j'ai du desactiver le control...

de plus je n'ai reussi que en donnant le login admin/pwd la connection anonyme qui suffit je n'arrive pas à l'utiliser..

Donc 2 possibilité: pacher le plugin... ou en ecrire un autre... je verais ca plus tard peut-etre que j'essairais demain, sinon ce sera apres mes vacances => debut novembre.

**Comment by scith** [comment]
Bonne idée le plugin spécifique YunoHost, ça éviterait d'avoir à bidouiller des sed en config. On a juste à l'autoinstall

**Comment by scith** [comment]
En fait voici je pense une idée de cahier des charges pour ce plugin "ynh_addressbooks":
Dans les options du plugin on propose d'activer ou non:
- Les utilisateurs YNH dans le carnet d'adresse
- Les contacts Baïkal de l'user
- Les contacts OwnCloud de l'user

Puis dans le plugin on rajoute dans les carnets d'adresse les contacts de chaque source si activé.
Ca permettrait de faire ça à un niveau global plutôt que de devoir bidouiller les confs de chaque utilisateur via des hooks pour rajouter leurs carnets baikal/owncloud. Un peu comme le plugin LDAP suggestion est sensé faire pour LDAP quoi (qu'on fixerait au passage avec ton trick)

Qu'en dites-vous ?

**Comment by Djip007** [comment]
Perso j'en ferais 3 plugins plutot qu'un compliqué:
- ynh_ldap_addressbooks        (sans parametre?)
- ynh_baikal_addressbooks      (avec l'URL baikal à entrer)
- ynh_owncloud_addressbooks (avec l'URL owncloud à entrer)

En suivant l'adage diviser pour mieux reigner ;). et il suffirait de choisir le (les) quel on active... 
je vais voir si j'ai le temps de faire le ynh_ldap_addressbooks à partir de LdapContactsSuggestions.php (ou ContactsExampleSuggestions.php) sinon ca sera apres mes vacances si personne ne l'a fait avant...

**Comment by scith** [comment]
Je maitrise pas du tout LDAP, mais je peux regarder pour les 2 autres

**Comment by Djip007** [comment]
OK on a qu'a faire comme ca.
 Moi non plus je maitrise pas LDAP (je regarde depuis 1 semaine ;) ) mais vu que ca existe en plus compliqué ca fait une bonne base donc je devrais m'en sortir faut juste un peu de temps.

**Comment by Djip007** [comment]
bon je vais faire qq essai...

**Comment by Djip007** [comment]
pour ownclood je suis tombé sur ca:
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/libraries/RainLoop/Providers/Suggestions/OwnCloudSuggestions.php
il faut p'etre l'adapter... mais c'est p'etre un bon debut...

**Comment by Djip007** [comment]
OK j'ai une version qui marche.... pull-request faite... vous pouvez tester.
- la recherche est faite dans 2 attribut: mail et DisplayName. on pourais en mettre d'autre (Login, ...etc) à voir.
- Je ne renvoie que le mail principale (il faut que je traite le cas des mail secondaire encore...) 

Par contre ca peu faire des chose bizard: si la recherche correspond à un mail secondaire, un contacte est suggéré avec son mail principal (qui potentiellement ne correspond pas à la recherche.)...

J'ai limité par default au 10er resultat (ou au nombre demandé par rainloop lors de l'appel) mais je n'ai pas assez de cas pour tester alors à verifier...

voila....

**Comment by Djip007** [comment]
Bon finalement j'ai ajouter les suggestion des mail secondaire... ca semble marcher.
Du coups je sais pas trop ce que tu va (peu?) recuperer dans le pull request.

**Comment by Djip007** [comment]
Un truc si tu fait un plugins... ce soir j'ai passé plus de temps à chercher un bug à la con qu'a coder:
le nom du repertoire ou est le plugins doit correspondre au nom de la Class du plugins:
repertoire= toto-titi  => classe=TotoTiti

Perso j'avais fait un une faute d'orthographe... et j'ai du passer 2h à comprandre pourquoi le plugin ne chargé pas...

**Comment by scith** [comment]
T'es on fire dis donc :laughing: 
J'ai pas le temps de m'y mettre tout de suite pour les 2 autres donc faudra attendre un peu. Merci pour la suggestion owncloud en tout cas ça a l'air pas mal ! Sinon je pensais piquer des trucs d'une librairie carddav

**Comment by scith** [comment]
Ah par contre c'est que des suggestions non ? Y'a moyen de rajouter ça dans le carnet d'adresses ?
Sinon pour OwnCloud et Baikal va falloir plutot faire des plugins addressbooks

**Comment by scith** [comment]
Bon on dirait que c'est pas simple de faire un plugin carnet d'adresses (plutôt que suggestions)... Il me semble que le comportement du plugin Rainloop pour OwnCloud est de carrément désactiver le lien vers le carnet d'adresse dans Rainloop pour forcer l'utilisateur à gérer ses contacts dans OwnCloud.
Du coup question, doit-on:
- Faire des plugins Owncloud et Baikal suggestions et désactiver le carnet d'adresse pour forcer l'utilisateur qui choisit d'utiliser Owncloud ou Baikal pour ses contacts à passer par ces carnets-là
- Ou ne pas faire de plugin et retourner à l'idée de départ qui était de préparamétrer le carnet d'adresse Owncloud ou Baikal à la création d'user via hook?

**Comment by Djip007** [comment]
J'avoie je me sert pas des carnet d'adresse du coups les suggestions ca me va. d'ailleur pour le ldap je sais pas si c'est interessant de rajouter tous les utilisateurs du ldap dans le carnet.
j'ai pas verifié, je pensais que quand on faisait une recheche dans le carnet d'adresse il ajoutais les resultats des suggestion... 
D'ailleur mon plugins n'as pas le bon nom... faudra corriger ca... 

Apres deja faire plugins suggestion pour  Owncloud/Baikal ca me semble un bon debut. et ca poura toujours servir.
Pas la peine de desactiver le carnet de rainloop pour l'instant.

**Comment by scith** [comment]
OK je fais tout ça alors :)
Merci

**Comment by Djip007** [comment]
J'ai vu que tu avais mis l'activation du plugins parametrable à l'install. cool!
Juste dans "Upgrade" tu copie 2 fois ynh-login-mapping ;)

**Comment by scith** [comment]
Oups je corrige merci !

**Comment by Djip007** [comment]
Fait juste un fetch/rebase... j'ai deja corrigé sous Github... sinon tu vas avoir un conflit :smile:
