### ISSUE TITLE
400Mo de log!

### ISSUE THREAD

**Issue by maniackcrudelis** [scith/rainloop_ynh#22]
Salut,

tout d'abord, je voulais signaler que le dépôt rainloop dans YunoHost-Apps n'a pas les issues activées. D'où l'issue ici.

Et donc, je viens de constater que rainloop écrit ses propres logs dans `data/_data_[...]/_default_/logs/`
Pour un total à ce jour de 400Mo me concernant sur environ 6 mois. Or ce sont des logs totalement inutile pour l'utilisateur.
Je vous le signale donc, et cherche de ce pas comment arrêter cette production insensée de log!

**Comment by maniackcrudelis** [comment]
[logs]
; Enable logging
enable = Off

dans `_default_/configs/application.ini`

OK, désolé les gars, je viens de constater que vous l'aviez déjà fait
https://github.com/scith/rainloop_ynh/blob/master/conf/data/configs/application.ini#L158
Il serait peut-être temps que je migre sur votre package!

**Comment by M5oul** [comment]
J’ai ouvert les logs sur le dépôt de YunoHost-Apps.

**Comment by maniackcrudelis** [comment]
Merci M5oul, c'est vrai que j'aurais pu le faire...

**Comment by Djip007** [comment]
Merci @M5oul ...
pour des versions plus a jour:
https://github.com/YunoHost-Apps/rainloop_ynh  : teste et utilisé
https://github.com/YunoHostPlugins-Testing/rainloop_ynh : version en dev... l'appli rainloop est plus à jours mais je n'ai pas trop eu le temps de trop tester...
