### ISSUE TITLE
SSO for user where mail_id (from mail_id@domaine) differe from ynh_id (login)

### ISSUE THREAD

**Issue by Djip007** [scith/rainloop_ynh#7]
Creation d'un plugins ynh-login-mapping (ou mieux? ldap-login-mapping)

Pourquoi je veux recuperer le login... parce que j'ai un prenom jean-philippe.... et un mail en jean-philippe@domaine.ext... sauf qu'il est pas possible de creer un compte ynh jean-philippe... (le "-" est pas autorisé... du coups je suis obligé de creer un compte en jean_philippe... mais une fois la, le login de connection imap pour la boite jean-philippe@domaine.ext est jean_philipe.... ce que rainloop n'aime pas du tout... De plus comme on a toutes les infos je trouve domage d'utiliser le plugin presant quand rainloop qui necessite de definir les infos depuis l'admin pour chaque compte.

Si il y a les infos general de ynh dans $_SERVER... ca permetrais de faire un plugins plus simple...

Ce que je ma demande c'est si on recupere tout meme depuis un plugin rainloop. si c'est le cas c'est cool... je vais re-essayer... j'avais tenter de voir $_SERVER['HTTP_EMAIL'] depuis un plugin mais y avait rien... mais j'avais p'etre fait des erreurs...

**Comment by scith** [comment]
On peut aussi préconfigurer le plugin "custom-login-mapping" pour qu'il fasse ce que tu veux ?
jean_philippe@domain.ext:jean-philippe@domain.ext

Par contre j'ai toujours pas saisi le soucis de jean_philippe vs. jean-philippe : le SSO rainloop se base sur le champs "email" de Yunohost et pas sur l'utilisateur. Dans ce champs tu peux très bien mettre des tirets
![tiret](http://tof.canardpc.com/view/85ad44dd-8411-498a-b5d2-3e950e20d9e0.jpg)

Par contre effectivement je ne sais pas si le serveur mail local suit. Pour un serveur mail externe (paramétré dans rainloop) pas de problème

**Comment by Djip007** [comment]
c'est exactement ca. pas de probleme sur un serveur externe... le probleme est sur le mail local.
- si tu essai de te connecté au SSO rainloop il essai jean-francois... et le serveur imap de ynh lui refuse puisqu'il attand scith... (a moins que tu ai comme moi changé la config par defait de dovecot sur ynh;)) 
- et oui on peu contourner ca avec custom-login-mapping mais je tiens pas à rentrer toutes les exceptions alors que l'on peu le faire ;)

ps: j'ai oublié de mettre le Labels... je trouve pas comment le rajouter...

**Comment by scith** [comment]
Hm je vois... Mais en fait je sais pas trop si le plugin développé pour ce cas de figure serait différent du "custom-login-mapping" ?
Parce qu'on peut toujours faire en sorte qu'à l'installation de l'app ainsi qu'à l'ajout d'un utilisateur, la ligne de custom-login-mapping se rajoute toute seule. Dans ce cas là rien à faire non ?
- Je rajoute l'utilisateur scith avec pour mail jean-francois@domain
- Rainloop rajoute dans custom-login-mapping *jean-francois@domain:scith*
- Je supprime l'utilisateur scith, Rainloop retire la ligne

Ca irait ?

**Comment by Djip007** [comment]
Ca marche aussi... mais faut aussi penser au cas ou on change le mail de l'utilisateur... etc ;)

par contre faudra faire gaffe a ce que que qq'un voudrais y mettre en plus.
Si on peu recuperer $_SERVER depuis le plugin je peu arriver à faire le plugin rapidement... 

pour le plugins : ca tient en un fichier index.php:
<?php
class YnhLoginMappingPlugin extends \RainLoop\Plugins\AbstractPlugin {
	public function Init()
	{
		$this->addHook('filter.login-credentials', 'FilterLoginСredentials');
	}
	/**
	 * @param string $sEmail
	 * @param string $sLogin
	 * @param string $sPassword
	 *
	 * @throws \RainLoop\Exceptions\ClientException
	 */
	public function FilterLoginСredentials(&$sEmail, &$sLogin, &$sPassword)
	{
            // en entrée tu as les infos que tu a donnée au sso (avec Login==Email[@domain?])
            // en sortie il fait modifier $sLogin => scith...  $_SERVER['HTTP_LOGIN']???
	}
	
}

Ca casse pas 3 pate à un canard ;) pour moi plus simple que de parser la chaine de parametrage du plugins pour retirer / modifier le mail ;) mais bon c'est du php... pas du scripte ;)

Bon si on a pas accé a $_SERVER faut passer par l'ldap et la plus chaud...
à voir dans ce cas apres https://github.com/scith/rainloop_ynh/issues/2

**Comment by scith** [comment]
Ah en effet je pensais pas que ce serait aussi facile :+1: 
A tester mais je pense que tu y as accès car avec nginx elles sont partout :monkey_face: 

Normalement avec $_SERVER tu as direct le login YNH, le mail et le pass en clair ...

**Comment by Djip007** [comment]
Je vais voir ca... si j'y arrive du coups pour la sso tu pourais ne pas envoyer le vrais login/mdp mais qq chose comme: "mail:ynh@sso / pwd:auto".
Si je vois ces valeurs alors je les remplaces par les données dans $_SERVEUR.

**Comment by Djip007** [comment]
Bon j'ai un peu avancer. comme je suis pas sur recuperer les info depuis $_SERVEUR (et puis que ca me fait decouvrir ldap) j'essai avec.
depuis le serveur en PHP c'est assez simple finalement pour y lire les infos...
voila pour recupere l'identifiant utilisateur depuis le mail ca donne ca:

```php
$email = 'mail@domaine.ext';

$cnx  = ldap_connect() or exit(">>Could not connect to LDAP server<<"); // en local rien de plus
$bind = ldap_bind($cnx); // en lecture connection anonyme OK...

$dn = "dc=yunohost,dc=org";  // la base ldap de yunohost...
$filter="(&(objectClass=inetOrgPerson)(mail=$email))";  // le filtre...
$justthese = array("uid", "mail");  // la liste des element que l'on veux recuperer (uid suffit ici)

$sr=ldap_search($cnx, $dn, $filter, $justthese) or exit(">>Recherche error<<");
$result = ldap_get_entries($cnx, $sr);
$user_id=$result[0]["uid"][0];  // voila normelemnet toujours 1 seultat et un seul... donc sans control ... (faudra en faire quand meme pour l'appli final...) 

// echo $result["count"]." entries returned\n"; // pour voir le nombre de resultats...
 print($user_id);  // OK un simple affichage pour l'instant... 
```

**Comment by Djip007** [comment]
Bon demain j'essai de mettre ca dans le plugins... (et remettre la conf normal de dovecot... pour ca faudra que je me rappel comment j'avais fait ;) comme d'hab j'ai pas noté....)

**Comment by Djip007** [comment]
OK le plugins marche... j'ai commité les sources https://github.com/Djip007/rainloop_ynh
Pour l'instant j'ai fait simple:
- recuperation des infos sur le ldap local...
- si le mail est trouvé on utilise l'uid de l'utilisateur pour se connecté... du  coups si c'est un mail externe il ne sera plus possible de ce connecté... 

reste:
 - modifier l'install...
 - traiter le cas des mail extern...

**Comment by Djip007** [comment]
Bon demain j'essairais la suite...
- essayer de tenir compte du domaine pour ne pas utiliser l'uid si c'est un mail extern... sous ldap:
virtualdomain=????,ou=domains,dc=yunohost,dc=org
- mettre a jour le fichier d'install... en attandant il faut copier le repetoire ynh-login-mapping (presant sous sources/plugins/) vers var/www/rainloop/data/[...]/plugins/.

si qq'un veux essayer qu'il n'hesite pas à me remonter les problemes/commentaire.

**Comment by scith** [comment]
Pas mal du tout, je vais tester ça !
Pour le mail externe on peut déjà dire que si l'adresse mail est pas dans la liste il ignore (ce qui autoriserait à se connecter depuis l'interface sur une boite mail non présente dans YNH).
Concernant mon cas particulier, c'est trop particulier pour avoir besoin d'une customisation je pense. J'aurai juste à désactiver ton plugin :)

Qu'en penses-tu ?

**Comment by Djip007** [comment]
Je pense que ce que tu propose est deja OK (pas testé...): Je cherche le mail rentré dans le login de rainloop (à la main ou par sso) dans la base ldap de ynh... si je ne le trouve pas le plugin ne fait rien. Donc je dirais que c'est bon avec gmail....
=> donc je vais surtout ce soir essayer de modifier le scripte d'install pour que le plugins soit:
  1- installé avec rainloop
  2- voir à l'activé par defaut... (si personne n'y vois d'objection...)

- Pour ton cas je pensais:
Si j'ai bien compris tu as indiqué pour un utilisateur, un mail qui n'est pas géré par ynh... c'est bien ca? 
Dans la base ldap il y a la liste des domaines.... dans ton cas le mail que tu utilise n'est pas dans les domaine ldap de ynh c'est toujours ca?
Si oui ce que je pensais c'est rajouter un controle sur le nom de domaine pour ne traiter que les cas des domaines presant dans le ldap de ynh.

**Comment by scith** [comment]
Si mon domaine est dans la liste LDAP mais j'utilise pas la boîte mail postfix. Mes DNS sont configurés pour que mes mails soient gérés ailleurs (par OVH).
Donc je vois pas trop comment on pourrait détecter ça ? Mais comme dit pas très important je pense, je dois être le seul à faire ça ... C'est surtout intéressant si on veut pas se tracasser à auto-héberger ses emails mais qu'on préfère laisser faire un prestataire.

**Comment by Djip007** [comment]
OK.... 
Bon j'ai bien avancer ce soir (faut que j'aille dormir maintenant...) au programme
- install automatique du plugins
- activation automatique
- j'ai corriger le nom de l'utilisateur de la base mysql (db_user/rainloop) ;)
- j'ai ajouter le code de rainloop (quand j'ai voulu tester il y avait une nouvelle version...) et ma version de sso doit connaitre la version... mais bon faudrait la recupere de data/VERSION plutot...
- j'ai deplacé les sed pour qu'il soit fait sur la copie et pas sur les elements recupere
- j'ai repris la recuperation de domaine (la commande de yunohost ne renvoie pas le meme format s'il y a 1 domaine ou plusieur... => j'utilise ldapsearch directement
- j'ai mais dans le repertoire sources/sso ma version...
- le MDP admin est maintenant passé en parametre au scripte de configuration (avec le path de l'API)

et j'ai encore essayer de ne pas mettre les elements dans /app.... mais tant que ssowat ne sera pas mis à jour ca ne peu pas marcher...
le sso se fait en tapant l'addresse: https://domaine.net/rainloop/?auto_log

Il faudra surement utiliser ta solution en attandant... mais je n'ai pas eu le temps de tester avec... 
mais vu comment j'ai fait les modifications ca doit etre facile de revenir a ta version... il ne doit y avoir que l'install à modifier (un commentaire à deplacer, et copier ta version de sso plutot que la mienne)

Si qq'un peu essayer je prand toutes les remarques ;)...

**Comment by Djip007** [comment]
Bon j'ai remis ta gestion de sso...
+ qq ptites modification...

**Comment by Djip007** [comment]
reste à filtrer les mail avec les domaines ynh... si besoin.

**Comment by scith** [comment]
Ca semble pas mal :) J'ai pas vraiment testé avec le jean-philippe mais je te fais confiance là-dessus vu que ça couvre ton besoin !
