### ISSUE TITLE
manage rainloop source

### ISSUE THREAD

**Issue by Djip007** [scith/rainloop_ynh#8]
Incude rainloop release here for more control on update

**Comment by Djip007** [comment]
Perso j'aurais bien fait une branche avec un repertoire sources et y extaire les sources de la version courante. et la tagé avec so noumero de version...

apres y a plus qu'a le mettre a jours a chaque release de rainloop...

**Comment by Djip007** [comment]
J'ai inclu le dernier zip dans ma version... 
Par contre j'aurais envie d'u mettre les versions decompressé... ca permetrait de suivre les modification... et eventuelement patcher si besoin... vous en pensez quoi?

**Comment by maniackcrudelis** [comment]
De mon expérience, j'avais cessé d'inclure les sources dans leur ensemble à cause de git, qui avait zappé quelques fichiers. Et qui ignorait parfois les fichiers cachés. Ce qui est difficile à vérifier, surtout lors d'une mise à jour des sources.
J'ai donc pris l'habitude d'inclure les sources en tar.gz et les patch dans un dossier adjacent pour les inclure lors de l'install.
Ça permet d'une part d'assurer l'intégrité des sources et d'autres part d'afficher clairement les patch ajoutés.

**Comment by Djip007** [comment]
Oui on vas commancer comme ca ;) en referencant et tagant les versions rainloop integré...
Sinon sous quel forme tu gere les patch?

**Comment by maniackcrudelis** [comment]
J'entends par patch, bien entendu, les modif du code source d'origine que j'applique pour l'adapter au package Yunohost.
Soit je les traite au sed depuis le script d'install, soit je garde le fichier modifié dans un dossier à côté de la source compressée. Et je remplace le fichier d'origine par la version patchée après extraction.

C'est surtout par soucis de transparence, les patch sont visibles tout de suite.
Et par facilité, ça m'évite de retoucher les sources en cas de mises à jour. J'ai juste à remplacer l'archive.

**Comment by Djip007** [comment]
OK tu n'utilise pas diff/patch ;)
Bon donc c'est ce que je fait aussi pour l'instant...

**Comment by Djip007** [comment]
OK les sources sont en conf... et les "patch" marche pour moi.

**Comment by scith** [comment]
Merci @Djip007 :+1:
